config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :jobs, only: [ :new, :create, :show, :create, :edit, :destroy, :update, :index] do
  resources :industries, only: [:show]

  end
  resources :users, only: [ :show, :edit, :index] do
    resources :favourites, only: [:create, :index ]
  end
  resources :favourites, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :job
  validates_uniqueness_of :job_id, scope: :user_id
  # acts_as_list
end

app/models/industry.rb
class Industry < ApplicationRecord
  has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :recommendations
  has_many :subjects, through: :recommendations
  has_one_attached :video
  belongs_to :user
  has_many :users, through: :favourites
  belongs_to :industry

  validates :title, presence: true
  validates :average_salary, presence: true
  validates :duties, presence: true
  validates :best_bits, presence: true
  validates :worst_bits, presence: true
  validates :qualifications, presence: true

end

app/models/jobs_tags.rb
class JobsTags < ApplicationRecord
  belongs_to :job
  belongs_to :tag
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :job
  belongs_to :subject
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :recommendations
  has_many :jobs, through: :recommendations
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :jobs, through: :jobs_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favourites
  has_many :favourite_jobs, through: :favourites, source: :job

  validates :email, presence: true
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :email, uniqueness: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:worker, :username])
  end

end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    @user = current_user
    @favourites = @user.favourites
  end

  def create
    @job = Job.find(params[:job_id])
    if current_user.favourite_jobs.include?(@job)
      redirect_to user_favourites_path, notice: "Job already favourited."
    else
      favourite = Favourite.new(user: current_user, job: @job)
      favourite.save!
      redirect_to job_path(@job)
    end
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    @favourite.destroy
    redirect_back_or_to "/"
  end

  private

  def favourite_params
    params.require(:favourite).permit(:user_id, :job_id, :position)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: :show

  def index
    @industries = Industry.all
    @subjects = Subject.all
    if params[:query].present? && @industries.exists?(name: "#{params[:query].capitalize}")
      industry_name = params[:query]
      found_jobs = Job.joins(:industry).where("LOWER(industries.name) LIKE ?", "%#{industry_name.downcase}%")
      @results = found_jobs
    elsif params[:query].present? && @subjects.exists?(name: "#{params[:query]}")
      subject_name = params[:query]
      @subject = Subject.where("LOWER(subjects.name) LIKE ?", "%#{subject_name.downcase}%").first
      if @subject.jobs.empty?
        @results = []
        @jobs = Job.all
      else
        @results = @subject.jobs
      end
    else
      @results = []
      @jobs = Job.all
    end
  end

  def show
    # raise
    # @industry = Industry.find_by_id(params[:id])
    @favourite = Favourite.find_by(user: current_user, job_id: params[:id])
  end

  def new
    @job = Job.new
    @industries = Industry.all
    @subjects = Subject.all
  end

  def create
    @job = Job.new(job_params)
    @job.user_id = current_user.id
    if @job.save
      redirect_to job_path(@job)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def job_params
    params.require(:job).permit(:title, :average_salary, :duties, :best_bits, :worst_bits, :qualifications, :video, :degree, :alternative, :industry_id, subject_ids: [])
  end

  def set_job
    @job = Job.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @array = Job.all
    @jobs = @array.shuffle
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    @favourites = Favourite.all
  end

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/favourites/index.html.erb
  <div class="container user-profile-bg">

  <div class="user-profile-card p-2 my-4">

  <div class="user-profile-head d-flex">

    <h1> <i class="fa-solid fa-circle-user"></i> <%= current_user.username %></h1>  <%= button_to "Logout", destroy_user_session_path, class: "btn btn-outline-light btn-sm", method: :delete %>
  </div>


<div class="current-banner">
  <div class="reused-banner-inner p-2 user-profile-head">
    <h1>My Favourite Jobs  💼  </h1>
    <hr>
    <% if @favourites.empty? %>
      <h3>You have no favourites yet!</h3>
    <% else %>
      <h3>You have <%= @favourites.count %> Favourite(s)</h3>
    <% end %>
  </div>
</div>



    <div data-controller="sortable" data-sortable-animation-value="150" id="results-fav">
      <% @favourites.each do |favourite| %>
      <div class ="job-profile-card d-flex justify-content-between m-2 row">
      <div class="job-profile-fav d-flex justify-content-between p-2">
      <div class="d-flex">
        <h3><%= favourite.job.title %></h3>

        </div>
          <div>

          <div class="btn-group btn-group-sm" style="align-items:center;" role="group" aria-label="Tools for favourites">

        <%= link_to "View", job_path(favourite.job), class: 'btn btn-primary'  %>
         <%= button_to "❌", favourite_path(favourite), method: :delete, class: 'btn btn-asdfoutline-light' %>
</div>
          </div>
        </div>
        </div>
      <% end %>

    </div>

  </div>

</div>

app/views/jobs/index.html.erb
<%= render partial: "layouts/logo" %>

  <div class="search-container">
    <% if @results.empty? %>
    <div class="results-head">
        <h3 style="color: white">No results for: <%= params[:query] %></h3>
      </div>
    <div class="row results-container" style="margin-top: 25px">
      <div class="col-sm result-card">
        <% @jobs.each do |job| %>
        <div class="card bg-dark">
          <%=cl_image_tag("#{job.video.key}.jpg", :resource_type => "video", class: 'result-card-image') %>
          <div class="card-img-overlay results-card-button">
            <h4 class="card-text"><%= job.title %></h4>
              <div class="d-flex justify-content-around">
                <%= link_to job_path(job), class: "p-2" do %>
                  <button type="button" style="color: white" class="align-content-end justify-content-center text-center btn-primary btn btn-outline-secondary p-2">View</button>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <% else %>
      <div class="results-head">
        <h3 style="color: white">Showing results for: <%= params[:query] %></h3>
      </div>
      <div class="row results-container" style="margin-top: 25px">
        <div class="col-sm result-card">
          <% @results.each do |result| %>
            <div class="card bg-dark">
              <%=cl_image_tag("#{result.video.key}.jpg", :resource_type => "video", class: 'result-card-image') %>
              <div class="card-img-overlay results-card-button">
                <h4 class="card-text"><%= result.title %></h4>
                <div class="d-flex justify-content-around">
                  <%= link_to job_path(result), class: "p-2" do %>
                    <button type="button" style="color: white" class="align-content-end justify-content-center text-center btn-primary btn btn-outline-secondary p-2">View</button>
                  <% end %>
                </div>
              </div>
            </div>
        <% end %>
        </div>
      </div>
    <% end %>
  </div>
<br>
<br>

app/views/jobs/new.html.erb
<div class= "form-container">

  <%= simple_form_for @job do |f| %>
  <%= f.input :title %>
  <%= f.input :average_salary %>
  <%= f.input :duties %>
  <%= f.input :best_bits %>
  <%= f.input :worst_bits %>
  <%= "Degree Required?" %>
  <%= f.input :degree, as: :boolean  %>
  <%= f.input :qualifications %>
  <%= f.input :alternative, label: "Free Alternatives to Study? (Optional)" %>
  <%= f.input :industry_id, collection: @industries, label_method: :name, label: "Select Industry", include_blank: false, selected: @job.industry_id %>
  <%= f.input :subject_ids, as: :check_boxes, collection: @subjects, label_method: :name, label: "Select Relevant Subjects (choose 3)", input_html: { min: 3, max: 3 }, include_blank: false, selected: @job.subject_ids %>
  <%= f.input :video, as: :file %>
  <%= f.hidden_field :user_id, :value=> "#{current_user.id}" %>
    <p class="text-center"><%= f.submit%></p>
  <% end %>
</div>
<br>
<br>
<br>

app/views/jobs/show.html.erb
<%= render "shared/job_profile" %>

app/views/layouts/_logo.html.erb
<div>
    <h1 class="app-logo">Wot2Be</h1>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-whole" data-controller="navbar">
  <div class="search-bar d-none" id="search-bar">
    <%= form_with url: jobs_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search by industry or subject"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
    <% end %>
  </div>
  <nav class="navbar" >
    <a class="nav-item"  <%= 'active' if current_page?(root_path) %>href="/">
      <i class="fa-solid fa-house nav-icon"></i>
    </a>
    <button class="nav-item" data-action="click->navbar#revealSearch" id="search-btn">
      <i class="fa-solid fa-magnifying-glass nav-icon"></i>
    </button>
    <% if user_signed_in? %>
      <a class="nav-item"<%= 'active' if current_page?(user_path(current_user)) %>href="/users/<%= current_user.id%>/favourites/">
        <i class="fa-solid fa-user nav-icon"></i>
      </a>
    <% else %>
      <a class="nav-item"<%= 'active' if current_page?(new_user_registration_path) %>href="/users/sign_up">
        <i class="fa-solid fa-user nav-icon"></i>
      </a>
    <% end %>
    <% if user_signed_in? && current_user.worker == true %>
      <a class="nav-item"<%= 'active' if current_page?(new_job_path) %>href="/jobs/new">
        <i class="fa-regular fa-square-plus nav-icon"></i>
      </a>
    <% end %>
  </nav>
</div>

<script>
var searchButton = document.getElementById("search-btn")
var searchBar = document.getElementById("search-bar")
searchButton.addEventListener( 'click', () =>
  searchBar.classList.toggle('d-none'))
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WOT2BE</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Red+Hat+Display&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/0baa16ec68.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "https://unpkg.com/cloudinary-video-player@1.9.9/dist/cld-video-player.light.min.css" %>
    <%= javascript_include_tag "https://unpkg.com/cloudinary-video-player@1.9.9/dist/cld-video-player.light.min.js" %>
  </head>
  <body>
    <%= render "shared/flashes" %>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render partial: "layouts/logo" %>

<div class="video-container">
<% @jobs.each do |job| %>
    <div class="video-div">
        <video
        id="demo-player-<%= job.id %>"
        autoplay
        muted
        class="cld-video-player video"
        data-cld-public-id="<%= job.video.key %>">
        </video>

        <%= link_to job_path(job), action:'show' do %>
          <i class="fa-solid fa-circle-info info-link"></i>
        <% end %>

        <div class="job-infos">
          <div class="job-user">
            <h5>Uploaded by <%= job.user.username %></h5>
          </div>
          <div class="job-detail-thumb">
            <p><%= job.title %></p>
          </div>
        </div>
    </div>
  <% end %>
</div>


<% @jobs.each do |job| %>
<script>
var demoplayer = cloudinary.videoPlayer('demo-player-<%= job.id  %>', { cloud_name: "dnn2gysbs",
 loop: true,
 })
</script>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_job_profile.html.erb
<%= render partial: "layouts/logo" %>

<div class="job-profile-container">
  <div class="profile-show">
    <div class="title-card">
      <h1><span class="job-title"><%= @job.title %></span></h1>
      <h3 class="job-user-show"><em><%= @job.user.username %></em></h3>
    </div>
    <div class="job-profile-nav">
      <div class="profile-nav-btn" id="overview-btn">
        <h4>Overview</h4>
      </div>
      <div class="profile-nav-btn " id="pros-btn">
        <h4>Pros/Cons</h4>
      </div>
      <div class="profile-nav-btn " id="how-btn">
        <h4>How2Be</h4>
      </div>
    </div>
    <div class="job-details-card" id="overview">
      <h3>Industry</h3>
      <h4><%= @job.industry.name %></h4>
      <br>
      <h3>Average Salary</h3>
      <h4>£<%= @job.average_salary %></h4>
      <br>
      <h3>Main Duties</h3>
      <h4><%= @job.duties %></h4>
    </div>
    <div class="job-details-card" id="pros-and-cons">
      <h3>Best Bits</h3>
      <h4><em>"<%= @job.best_bits %>"</em></h4>
      <br>
      <h3>Worst Bits</h3>
      <h4><em>"<%= @job.worst_bits %>"</em></h4>
    </div>
    <div class="job-details-card " id="how-to-be">
    <h3>Degree Required?</h3>
    <% if @job.degree == true %>
      <h4>Yes</h4>
    <% else %>
      <h4>No</h4>
    <% end %>
    <h3>Relevant Degree</h3>
    <h4><%= @job.qualifications %></h4>
    <br>
    <% if @job.alternative.present? %>
      <h3>Options for low-income students</h3>
      <h4><%= @job.alternative %></h4>
    <% end %>
    <br>
    <h3>Recommended Subjects</h3>
      <div class="job-subjects">
      <% @job.subjects.each do |subject| %>
        <%= link_to "##{subject.name}", jobs_path(query: subject.name), class: 'subject-link' %>
      <% end %>
      </div>
    </div>

    <% if @favourite %>
    <%= link_to favourite_path(@favourite), data: { turbo_method: :delete, turbolinks: true}, class: 'remove-style' do %>
      <div class="job-details-card job-favorite" id="favourited">
        <i class="fa-solid fa-heart heart-fav-link"></i>
        <h1 class="my-1">Job Saved to favourites!</h1>
      </div>
    <% end %>
    <% else %>
      <%= link_to user_favourites_path(user_id: current_user.id, job_id: @job.id), data: { turbo_method: :post, turbolinks: true}, class: 'remove-style' do %>
      <div class="job-details-card job-favorite" id="not-favourited">
          <i class="fa-regular fa-heart heart-fav-link"></i>
          <h1 class="my-1">Add to favourites!</h1>
      </div>
      <% end %>
    <% end %>
      <br>
      <br>
    </div>
  </div>
</div>


<style>
.job-profile-container {
  background-image: url(<%= @job.industry.image_url %>)
}
</style>

<script>
var overviewButton = document.getElementById("overview-btn")
var prosButton = document.getElementById("pros-btn")
var howButton = document.getElementById("how-btn")
var overviewCard = document.getElementById("overview")
var prosCard = document.getElementById("pros-and-cons")
var howCard = document.getElementById("how-to-be")

  overviewButton.classList.add('active');
  overviewCard.classList.remove('d-none');
  prosCard.classList.add('d-none')
  howCard.classList.add('d-none')
  overviewButton.addEventListener('click', () => {
    deactivateAll();
    overviewButton.classList.add('active');
    overviewCard.classList.remove('d-none');
  });

  prosButton.addEventListener('click', () => {
    deactivateAll();
    prosButton.classList.add('active');
    prosCard.classList.remove('d-none');
  });

  howButton.addEventListener('click', () => {
    deactivateAll();
    howButton.classList.add('active');
    howCard.classList.remove('d-none');
  });

  function deactivateAll() {
    overviewButton.classList.remove('active');
    prosButton.classList.remove('active');
    howButton.classList.remove('active');
    overviewCard.classList.add('d-none');
    prosCard.classList.add('d-none');
    howCard.classList.add('d-none');
  }
</script>

app/views/users/show.html.erb
<div class="container">
  <div class="user-profile-card p-2 my-4">
    <div class="user-profile-head">
      <h1>Profile: <%= current_user.username %></h1>
    </div>

    <%= button_to "Logout", destroy_user_session_path, class: "btn btn-secondary btn-lg", method: :delete %>

 <% if user_signed_in? && current_user.worker == false %>
      <%= button_to "Favourites", user_favourites_path(current_user), class: "btn btn-secondary btn-lg" %>
    <% end %>

  </div>
</div>